import React from 'react';

export function GlossaryPage() {
  return (
      <div style={{margin: "1in"}}>
		<h2>De la transcripción</h2>
		<p>Al inicio del proyecto se decidió hacer dos tipos de transcripción: una cercana al habla de los entrevistados (transcripción superficial) y otra que diera cuenta de las raíces y demás morfemas de la lengua (transcripción profunda). Esta decisión se tomó ya que cada una presenta ventajas y desventajas para distintos usuarios. Una transcripción más cercana al habla del entrevistado permite apreciar diversos procesos tales como: las elisiones, contracciones, asimilaciones, entre otras. Varios de estos fenómenos dan lugar a formas que no serían reconocibles para los no expertos. En cuanto a la transcripción profunda, ésta tiene la ventaja de representar morfemas fáciles de reconocer, y de encontrar en otras obras de referencia, como los diccionarios. Además, es posible a partir de ésta llevar a cabo otras tareas lingüísticas, como el corte morfológico y el glosado. Pero tiene la desventaja de no coincidir con el habla de los entrevistados. Veamos los siguientes ejemplos:</p>
		<table>
  			<tr>
    			<td><b>transcripción superficial</b></td>
    			<td><i>nojchu paylaile’, pos maanlup’ée kiilo yiiki</i></td>
  			</tr>
  			<tr>
    			<td><b>transcripción profunda</b></td>
    			<td><i>nojoch u paylaile’, pos maanal jump’éel kiilo yiikil</i></td>
  			</tr>
    		<tr>
    			<td><b>traducción</b></td>
    			<td>está grande la payla, pues más de un kilo de chile</td>
  			</tr>
		</table>
		<p>Ambas transcripciones se realizaron con un alfabeto práctico que diera cuenta de todos los fonemas del maya yucateco actual, por esta razón se contemplaron los grafemas “d”, “g”, y “f”, para los fonemas [d], [g], y [f], respectivamente. Estos fonemas se encuentran en palabras prestadas de otras lenguas, pero que ya están totalmente integradas en el maya. Por ejemplo:</p>
		<table>
  			<tr>
    			<td><b>transcripción superficial</b></td>
    			<td><i>a laj desinfektaartik xan aantesa... a...</i></td>
  			</tr>
  			<tr>
    			<td><b>transcripción profunda</b></td>
    			<td><i>a láaj desinfektaartik xan aantes a... a...</i></td>
  			</tr>
    		<tr>
    			<td><b>traducción</b></td>
    			<td>a desinfectar todas antes de...</td>
  			</tr>
		</table>
		<p>Para cada sonido del habla se usó en la escritura la misma letra o conjunto de letras (grafías), salvo en algunos casos en la que se transcribe siguiendo el español estándar (por ejemplo, NN). Se usaron las siguientes grafías en las transcripciones realizadas en el proyecto:</p>
		<table>
  			<tr>
    			<th>fonema</th>
    			<th>grafía</th>
  			</tr>
  			<tr>
    			<td>[a]</td>
    			<td>a</td>
  			</tr>
  			<tr>
    			<td>[b]</td>
    			<td>b</td>
  			</tr>
    		<tr>
    			<td>[ʧ]</td>
    			<td>ch</td>
  			</tr>
   			<tr>
    			<td>[ʧʼ]</td>
    			<td>ch’</td>
  			</tr>
  			<tr>
    			<td>[d]</td>
    			<td>d</td>
  			</tr>
    		<tr>
    			<td>[e]</td>
    			<td>e</td>
  			</tr>
  			<tr>
    			<td>[f]</td>
    			<td>f</td>
  			</tr>
  			<tr>
    			<td>[g]</td>
    			<td>g</td>
  			</tr>
    		<tr>
    			<td>[i]</td>
    			<td>i</td>
  			</tr>
   			<tr>
    			<td>[h]</td>
    			<td>j</td>
  			</tr>
  			<tr>
    			<td>[k]</td>
    			<td>k</td>
  			</tr>
    		<tr>
    			<td>[k’]</td>
    			<td>k’</td>
  			</tr>
   			<tr>
    			<td>[l]</td>
    			<td>l</td>
  			</tr>
  			<tr>
    			<td>[m]</td>
    			<td>m</td>
  			</tr>
    		<tr>
    			<td>[n]</td>
    			<td>n</td>
  			</tr>
   			<tr>
    			<td>[o]</td>
    			<td>o</td>
  			</tr>
  			<tr>
    			<td>[p]</td>
    			<td>p</td>
  			</tr>
    		<tr>
    			<td>[p’]</td>
    			<td>p’</td>
  			</tr>
   			<tr>
    			<td>[r]</td>
    			<td>r</td>
  			</tr>
  			<tr>
    			<td>[s]</td>
    			<td>s</td>
  			</tr>
    		<tr>
    			<td>[t]</td>
    			<td>t</td>
  			</tr>
   			<tr>
    			<td>[t’]</td>
    			<td>t’</td>
  			</tr>
  			<tr>
    			<td>[ts]</td>
    			<td>ts</td>
  			</tr>
    		<tr>
    			<td>[ts’]</td>
    			<td>ts’</td>
  			</tr>
  			<tr>
    			<td>[u]</td>
    			<td>u</td>
  			</tr>
  			<tr>
    			<td>[w]</td>
    			<td>w</td>
  			</tr>
    		<tr>
    			<td>[x]</td>
    			<td>x</td>
  			</tr>
  			<tr>
    			<td>[y]</td>
    			<td>y</td>
  			</tr>
		</table> <table>
  			<tr>
    			<th>fonema</th>
    			<th>grafía</th>
  			</tr>
  			<tr>
    			<td>[a]</td>
    			<td>a</td>
  			</tr>
  			<tr>
    			<td>[b]</td>
    			<td>b</td>
  			</tr>
    		<tr>
    			<td>[ʧ]</td>
    			<td>ch</td>
  			</tr>
   			<tr>
    			<td>[ʧʼ]</td>
    			<td>ch’</td>
  			</tr>
  			<tr>
    			<td>[d]</td>
    			<td>d</td>
  			</tr>
    		<tr>
    			<td>[e]</td>
    			<td>e</td>
  			</tr>
  			<tr>
    			<td>[f]</td>
    			<td>f</td>
  			</tr>
  			<tr>
    			<td>[g]</td>
    			<td>g</td>
  			</tr>
    		<tr>
    			<td>[i]</td>
    			<td>i</td>
  			</tr>
   			<tr>
    			<td>[h]</td>
    			<td>j</td>
  			</tr>
  			<tr>
    			<td>[k]</td>
    			<td>k</td>
  			</tr>
    		<tr>
    			<td>[k’]</td>
    			<td>k’</td>
  			</tr>
   			<tr>
    			<td>[l]</td>
    			<td>l</td>
  			</tr>
  			<tr>
    			<td>[m]</td>
    			<td>m</td>
  			</tr>
    		<tr>
    			<td>[n]</td>
    			<td>n</td>
  			</tr>
   			<tr>
    			<td>[o]</td>
    			<td>o</td>
  			</tr>
  			<tr>
    			<td>[p]</td>
    			<td>p</td>
  			</tr>
    		<tr>
    			<td>[p’]</td>
    			<td>p’</td>
  			</tr>
   			<tr>
    			<td>[r]</td>
    			<td>r</td>
  			</tr>
  			<tr>
    			<td>[s]</td>
    			<td>s</td>
  			</tr>
    		<tr>
    			<td>[t]</td>
    			<td>t</td>
  			</tr>
   			<tr>
    			<td>[t’]</td>
    			<td>t’</td>
  			</tr>
  			<tr>
    			<td>[ts]</td>
    			<td>ts</td>
  			</tr>
    		<tr>
    			<td>[ts’]</td>
    			<td>ts’</td>
  			</tr>
  			<tr>
    			<td>[u]</td>
    			<td>u</td>
  			</tr>
  			<tr>
    			<td>[w]</td>
    			<td>w</td>
  			</tr>
    		<tr>
    			<td>[x]</td>
    			<td>x</td>
  			</tr>
  			<tr>
    			<td>[y]</td>
    			<td>y</td>
  			</tr>
		</table>
		<p>En el caso de las vocales se consideraron las siguientes formas:</p>
		<table>
  			<tr>
    			<th>corta</th>
    			<th>larga</th>
    			<th>alta</th>
    			<th>rearticulada</th>
    			<th>glotalizada</th>
  			</tr>
  			<tr>
    			<td>a</td>
    			<td>aa</td>
    			<td>áa</td>
    			<td>a’a</td>
    			<td>a’</td>
  			</tr>
  			<tr>
    			<td>e</td>
    			<td>ee</td>
    			<td>ée</td>
    			<td>e’e</td>
    			<td>e’</td>
  			</tr>
  			<tr>
    			<td>i</td>
    			<td>ii</td>
    			<td>íi</td>
    			<td>i’i</td>
    			<td>i’</td>
  			</tr>
  			<tr>
    			<td>o</td>
    			<td>oo</td>
    			<td>óo</td>
    			<td>o’o</td>
    			<td>o’</td>
  			</tr>
  			<tr>
    			<td>u</td>
    			<td>uu</td>
    			<td>úu</td>
    			<td>u’u</td>
    			<td>u’</td>
  			</tr>
  		</table>
  		<p>Los antropónimos se transcribieron usando la ortografía oficial en español. Por ejemplo:</p>
		<table>
  			<tr>
    			<td>transcripción</td>
    			<td><i>in kaaba’e’ Martín</i></td>
  			</tr>
    		<tr>
    			<td>traducción</td>
    			<td>mi nombre es Martín</td>
  			</tr>
		</table>
  		<p>Los topónimos se transcribieron a partir de la ortografía del maya y de acuerdo a su fonología. Por ejemplo:</p>
  		<table>
  			<tr>
    			<td><b>transcripción</b></td>
    			<td><i>in kaajale’ Póopla’</i></td>
  			</tr>
    		<tr>
    			<td><b>traducción</b></td>
    			<td>mi pueblo es Popolá</td>
  			</tr>
		</table>
      </div>
  );
}
