name: Prepare Upgrade
description: Creates a PR to upgrade LingView core to the newest stable version available.

env:
  upstream: BrownCLPS/LingView
  upstream_branch: prodready # master

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  check-repo:
    runs-on: ubuntu-latest
    outputs:
      is-core: ${{ github.repository == env.upstream }}
    steps:
      - run: echo "Checking if repository is the upstream repository..."
  check-comment:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@upgrade'
          reaction: hooray
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upgrade:
    needs: [check-repo, check-comment]
    if: needs.check-repo.outputs.is-core == 'false' && needs.check-comment.outputs.triggered == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v2
        with:
          ref: temp-master
      - name: Merge upstream into master
        run: |
          git remote add upstream "https://github.com/$UPSTREAM.git"
          git fetch upstream
          remote_head_hash=$(git rev-parse "upstream/$UPSTREAM_BRANCH")
          echo "::set-env name=remote_head_hash::$remote_head_hash"
          git merge --no-commit --no-ff "upstream/$UPSTREAM_BRANCH"
          git reset -- /data # revert any updates in data path
        env:
          UPSTREAM: ${{ env.upstream }}
          UPSTREAM_BRANCH: ${{ env.upstream_branch }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Upgrade LingView core version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Upgrade LingView Core'
          body: |
            Pull request to upgrade LingView version to master (${{ env.remote_head_hash }}) is ready to review and merge! Automatically ignored any changes made to the `data/` folder. 

            To deploy the newest version after merging this pull request, merge this repository's `master` branch into the `production` branch.

            _Auto-generated by [create-pull-request][1]_

            [1]: https://github.com/peter-evans/create-pull-request
          labels: automated pr
          branch: master/upgrade
